routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'GuestController@index');

Route::get('/about', 'GuestController@aboutUs');

Route::get('/contact-us', 'GuestController@contactUs');

Route::post('/contact-us/submit', 'GuestController@submitContactUs');

Route::get('/book-detail/{id}', 'GuestController@detail');

Route::get('/read/{id}', [
    'middleware' => ['auth', 'role:member|admin'],
    'uses'       => 'GuestController@read'
  ]);

Route::get('/search', 'SearchController@index');

Route::get('/category/{id}', 'SearchController@category');

Auth::routes();
Route::get('auth/verify/{token}', 'Auth\RegisterController@verify');
Route::get('auth/send-verification', 'Auth\RegisterController@sendVerification');

Route::get('/home', 'HomeController@index');
Route::get('settings/profile', 'SettingsController@profile');
Route::get('settings/profile/edit', 'SettingsController@editProfile');
Route::post('settings/profile', 'SettingsController@updateProfile');
Route::get('settings/password', 'SettingsController@editPassword');
Route::post('settings/password', 'SettingsController@updatePassword');


Route::group(['prefix'=>'admin', 'middleware'=>['auth', 'role:admin']], function () {
  
  Route::resource('authors', 'AuthorsController');
  
  Route::resource('books', 'BooksController');
  
  Route::resource('members', 'MembersController');

  Route::post('members/change-status/{id}', 'MembersController@changeStatus')->name('members.changeStatus');

  Route::resource('categories', 'CategoriesController');
  
  /*Route::get('statistics', [
    'as'   => 'statistics.index',
    'uses' => 'StatisticsController@index'
  ]);*/

  Route::get('export/books', [
    'as'   => 'export.books',
    'uses' => 'BooksController@export'
  ]);

  Route::post('export/books', [
    'as'   => 'export.books.post',
    'uses' => 'BooksController@exportPost'
  ]);

  Route::get('template/books', [
    'as'   => 'template.books',
    'uses' => 'BooksController@generateExcelTemplate'
  ]);

  Route::post('import/books', [
    'as'   => 'import.books',
    'uses' => 'BooksController@importExcel'
  ]);
  
});

Route::post('/subscribe', 'MailchimpsController@postSubscribe');

/*Route::get('books/{book}/borrow', [
  'middleware' => ['auth', 'role:member'],
  'as'         => 'guest.books.borrow',
  'uses'       => 'BooksController@borrow'
]);*/

/*Route::put('books/{book}/return', [
  'middleware' => ['auth', 'role:member'],
  'as'         => 'member.books.return',
  'uses'       => 'BooksController@returnBack'
]);*/

resources/views/layouts/_admin-menu.blade.php
<div class="col-lg-2 col-md-2 col-sm-4">
  <div class="bs-component">
    <h3>Menu</h3>
  </div>
  <div class="list-group table-of-contents">
    <a class="list-group-item {{{ (Request::is('home') ? 'active' : '') }}}" href="{{ url('/home') }}"> Dashboard</a>
    <a class="list-group-item {{{ (Request::is('admin/authors') ? 'active' : '') }}}" href="{{ route('authors.index') }}"> Penulis</a>
    <a class="list-group-item {{{ (Request::is('admin/categories') ? 'active' : '') }}}" href="{{ route('categories.index') }}"> Kategori</a>
    <a class="list-group-item {{{ (Request::is('admin/books') ? 'active' : '') }}}" href="{{ route('books.index') }}"> Buku</a>
    <a class="list-group-item {{{ (Request::is('admin/members') ? 'active' : '') }}}" href="{{ route('members.index') }}"> Member</a>
  </div>
</div>

resources/views/layouts/_flash.blade.php
@if (session()->has('flash_notification.message'))
  <div class="container">
    <div class="alert alert-{{ session()->get('flash_notification.level') }}">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      {!! session()->get('flash_notification.message') !!}
    </div>
  </div>
@endif

resources/views/layouts/_footer.blade.php
<!--footer-->
<div class="page-header"></div>

<footer class="footer1">
    <div class="container">
        <div class="row"><!-- row -->
            <div class="col-lg-4 col-md-4">
                <ul class="list-unstyled clear-margins">
                    <li class="widget-container widget_nav_menu">
                        <ul>
                            <li><a  href="{{ url('/about') }}"><i class="fa fa-angle-double-right"></i> About Us</a></li>
                            <li><a  href="{{ url('/contact-us') }}"><i class="fa fa-angle-double-right"></i> Contact Us</a></li>
                            <li>
                                {!! Form::open(['url' => '/subscribe']) !!}
                                    <div class="form-group form-group-sm">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="text" name="email" class="form-control" placeholder="Email Anda">
                                    </div>
                                    <button type="submit" id="submit" name="submit" class="btn btn-default btn-sm">Subscribe</button>
                                {!! Form::close() !!}
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<!--header-->

<div class="footer-bottom">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
				<div class="copyright">
					© 2017, {{ config('app.name', 'Laravel') }}, All rights reserved
				</div>
			</div>

			<!-- <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
				<div class="design">
                     <a href="#">Franchisee </a> |  <a target="_blank" href="http://www.webenlance.com">Web Design & Development by Webenlance</a>
                </div> -->
            <div class="col-xs-12 col-sm-6 col-md-offset-3 col-md-3 col-lg-offset-3 col-lg-3">
                <div class="social-icons pull-right">
                    <ul class="nomargin">
                        <a href="https://www.facebook.com/bootsnipp"><i class="fa fa-facebook-square fa-3x social-fb" id="social"></i></a>
                        <a href="https://twitter.com/bootsnipp"><i class="fa fa-twitter-square fa-3x social-tw" id="social"></i></a>
                        <a href="https://plus.google.com/+Bootsnipp-page"><i class="fa fa-google-plus-square fa-3x social-gp" id="social"></i></a>
                        <a href="mailto:bootsnipp@gmail.com"><i class="fa fa-envelope-square fa-3x social-em" id="social"></i></a>
                    </ul>
                </div>
			</div>
		</div>
	</div>
</div>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/font-awesome.min.css" rel='stylesheet' type='text/css'> 
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/app.css" rel="stylesheet">
    <link href="/css/jquery.dataTables.css" rel="stylesheet">
    <link href="/css/dataTables.bootstrap.css" rel="stylesheet">
    <link href="/css/selectize.css" rel="stylesheet">
    <link href="/css/selectize.bootstrap3.css" rel="stylesheet">
    <link href="/css/heroic-features.css" rel="stylesheet">

    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    <img src="../images/logo-digilib-badiklat.png">
                    {{-- {{ config('app.name', 'Laravel') }} --}}
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!--Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Kategori <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            @foreach($main_categories as $category)
                                <li><a href="{{ url('/category').'/'.$category->id }}">{{ $category->name }}</a></li>
                            @endforeach
                        </ul>
                    </li>
                    
                </ul>

                <form class="navbar-form navbar-left" role="search" action="{{ url('/search') }}" method="get">
                  <div class="form-group">
                    <input type="text" name="title" class="form-control" placeholder="Pencarian Judul Buku">
                  </div>
                  <button type="submit" class="btn btn-default">Cari</button>
                </form>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Daftar</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/home') }}"><i class="fa fa-btn fa-home"></i> Dashboard</a></li>
				<li><a href="{{ url('/settings/profile') }}"><i class="fa fa-btn fa-user"></i> Profil</a></li>
                                <li><a href="{{ url('/settings/password') }}"><i class="fa fa-btn fa-lock"></i> Ubah Password</a></li>
                                <li>
                                    <a href="{{ url('/logout') }}"
                                        onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @include('layouts._flash')

    @if ($message = Session::get('success'))
    <div class="alert alert-success alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button> 
            <strong>{{ $message }}</strong>
    </div>
    @endif

    @if ($message = Session::get('error'))
    <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button> 
            <strong>{{ $message }}</strong>
    </div>
    @endif

    @yield('content')

    @include('layouts._footer')

    <!-- Scripts -->
    <script src="/js/jquery-3.1.0.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/jquery.dataTables.min.js"></script>
    <script src="/js/dataTables.bootstrap.min.js"></script>
    <script src="/js/selectize.min.js"></script>
    <script src="/js/custom.js"></script>
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <script>
        $(function() {
            $("#datepicker").datepicker();
            $( "#datepicker" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
        });
    </script>
    @yield('scripts')
</body>
</html>